name: media_transfer_tool
description: A media transfer and organization tool built with Flutter Desktop
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI関連
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  flutter_staggered_grid_view: ^0.7.0
  
  # ファイル操作
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  desktop_drop: ^0.4.0
  
  # 画像処理
  image: ^4.1.3
  photo_manager: ^3.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  
  # 状態管理
  provider: ^6.1.1
  
  # ストレージ
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  
  # その他ユーティリティ
  intl: ^0.18.1
  crypto: ^3.0.3
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
